# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Build

on: 
  push:
    branches: 
      - staging-validation
  pull_request:
    branches: 
      - staging-validation  
jobs:
  validate:
    name: Validate staging action
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Scan test site
      uses: microsoft/accessibility-insights-action@v2.3.0-staging
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        site-dir: ${{ github.workspace }}/dev/website-root

    - name: Upload report artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: accessibility-reports
        path: ${{ github.workspace }}/_accessibility-reports
