# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Build

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '**'  
jobs:
  build:
    name: Build & check code styling
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Check copyright headers
      run: yarn copyright:check
    
    - name: Check code formatting
      run: yarn format:check
    
    - name: Build
      run: yarn cbuild
    
    - name: Check for lint errors
      run: yarn lint
  
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run tests
      run: yarn test --ci --coverage
      env:
        NODE_OPTIONS: --max_old_space_size=4096
     
    # - name: Publish code coverage
    #   if: github.event_name == 'pull_request'
    #   uses: 5monkeys/cobertura-action@master
    #   with:
    #     path: ${{ github.workspace }}/test-results/unit/coverage/cobertura-coverage.xml
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     minimum_coverage: 85%
    
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}

